import { prisma } from './prisma';

// 模拟数据生成器 - 为 Playbook Radar 创建高质量的测试数据
const mockData = {
  youtube: [
    {
      titleRaw: "Automate Your Entire Workflow with OpenClaw + Browser Control",
      titleCn: "用 OpenClaw + 浏览器控制自动化你的整个工作流",
      descriptionRaw: "Learn how to build a complete automation pipeline using OpenClaw's browser control features. We'll cover everything from basic selectors to multi-agent coordination.",
      descriptionCn: "学习如何使用 OpenClaw 的浏览器控制功能构建完整的自动化流水线。涵盖从基础选择器到多 agent 协调的全部内容。",
      url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      author: "Automation Mastery",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2), // 2 days ago
      heatScore: 8.5,
      views: 15420,
      likes: 892,
      comments: 156,
      tags: ["自动化", "浏览器控制", "coding"],
    },
    {
      titleRaw: "OpenClaw Multi-Agent Architecture Explained",
      titleCn: "OpenClaw 多 Agent 架构详解",
      descriptionRaw: "Deep dive into how OpenClaw orchestrates multiple agents for complex tasks. Perfect for building content factories and automation pipelines.",
      descriptionCn: "深入解析 OpenClaw 如何协调多个 agent 完成复杂任务。非常适合构建内容工厂和自动化流水线。",
      url: "https://www.youtube.com/watch?v=jNQXAC9IVRw",
      author: "AI Engineering Hub",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5),
      heatScore: 7.2,
      views: 8930,
      likes: 567,
      comments: 89,
      tags: ["多 agent", "自动化", "一人公司"],
    },
    {
      titleRaw: "Build a Content Factory with OpenClaw Webhooks",
      titleCn: "用 OpenClaw Webhooks 构建内容工厂",
      descriptionRaw: "Step-by-step tutorial on setting up webhook-triggered content generation pipelines. Automate your entire content creation workflow.",
      descriptionCn: "设置 webhook 触发的内容生成流水线的逐步教程。自动化你的整个内容创建工作流。",
      url: "https://www.youtube.com/watch?v=9bZkp7q19f0",
      author: "Content Automation Pro",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 12),
      heatScore: 9.1,
      views: 23150,
      likes: 1456,
      comments: 234,
      tags: ["webhook", "内容工厂", "自动化"],
    },
    {
      titleRaw: "OpenClaw Node Management Best Practices",
      titleCn: "OpenClaw 节点管理最佳实践",
      descriptionRaw: "Everything you need to know about managing OpenClaw nodes for production deployments. Scaling, monitoring, and troubleshooting.",
      descriptionCn: "管理 OpenClaw 节点进行生产部署所需了解的一切。扩展、监控和故障排除。",
      url: "https://www.youtube.com/watch?v=kJQP7kiw5Fk",
      author: "DevOps Daily",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 48),
      heatScore: 6.8,
      views: 5670,
      likes: 342,
      comments: 67,
      tags: ["节点/node", "coding", "自动化"],
    },
    {
      titleRaw: "From Zero to Hero: OpenClaw for Solo Founders",
      titleCn: "从零到英雄：一人公司必备的 OpenClaw 技能",
      descriptionRaw: "How solo founders can leverage OpenClaw to build automated businesses. Real examples and case studies included.",
      descriptionCn: "一人创始人如何利用 OpenClaw 构建自动化业务。包含真实案例和研究。",
      url: "https://www.youtube.com/watch?v=L_jWHffIx5E",
      author: "Solo Founder Stories",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 72),
      heatScore: 8.9,
      views: 18760,
      likes: 1123,
      comments: 198,
      tags: ["一人公司", "自动化", "内容工厂"],
    },
    {
      titleRaw: "Advanced Browser Automation with OpenClaw",
      titleCn: "OpenClaw 高级浏览器自动化",
      descriptionRaw: "Master advanced browser automation techniques including dynamic content handling, anti-detection, and parallel execution.",
      descriptionCn: "掌握高级浏览器自动化技术，包括动态内容处理、反检测和并行执行。",
      url: "https://www.youtube.com/watch?v=oHg5SJYRHA0",
      author: "Browser Automation Labs",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 6),
      heatScore: 7.5,
      views: 9840,
      likes: 623,
      comments: 112,
      tags: ["浏览器控制", "自动化", "coding"],
    },
    {
      titleRaw: "OpenClaw + Zapier: Ultimate Integration Guide",
      titleCn: "OpenClaw + Zapier：终极集成指南",
      descriptionRaw: "Connect OpenClaw to 5000+ apps using Zapier webhooks. Build powerful automation workflows without coding.",
      descriptionCn: "使用 Zapier webhooks 将 OpenClaw 连接到 5000+ 应用。无需编码即可构建强大的自动化工作流。",
      url: "https://www.youtube.com/watch?v=RgKAFk5djSk",
      author: "No-Code Automation",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 96),
      heatScore: 6.2,
      views: 4520,
      likes: 287,
      comments: 45,
      tags: ["webhook", "自动化", "一人公司"],
    },
    {
      titleRaw: "Scaling OpenClaw: From 1 to 100 Agents",
      titleCn: "扩展 OpenClaw：从 1 到 100 个 Agent",
      descriptionRaw: "Lessons learned from scaling OpenClaw deployments. Architecture patterns, performance tuning, and cost optimization.",
      descriptionCn: "扩展 OpenClaw 部署的经验教训。架构模式、性能优化和成本优化。",
      url: "https://www.youtube.com/watch?v=fJ9rUalIMbQ",
      author: "Scale Up Engineering",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 168),
      heatScore: 5.8,
      views: 3890,
      likes: 234,
      comments: 56,
      tags: ["多 agent", "节点/node", "coding"],
    },
  ],
  x: [
    {
      titleRaw: "Just shipped a new OpenClaw feature: webhook triggers for browser actions! 🚀",
      titleCn: "刚刚发布了新的 OpenClaw 功能：浏览器动作的 webhook 触发！🚀",
      descriptionRaw: "Now you can trigger complex browser automation workflows from any app. Game changer for content factories.",
      descriptionCn: "现在你可以从任何应用触发复杂的浏览器自动化工作流。内容工厂的游戏规则改变者。",
      url: "https://x.com/openclaw/status/1234567890",
      author: "@openclaw",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 3),
      heatScore: 8.7,
      views: 12450,
      likes: 892,
      comments: 156,
      tags: ["webhook", "浏览器控制", "自动化"],
    },
    {
      titleRaw: "OpenClaw tip: Use multi-agent mode for parallel content scraping 🧵",
      titleCn: "OpenClaw 技巧：使用多 agent 模式进行并行内容抓取 🧵",
      descriptionRaw: "Thread: How to set up 10 agents to scrape 1000 pages in minutes. Includes code snippets and best practices.",
      descriptionCn: "主题：如何设置 10 个 agent 在几分钟内抓取 1000 个页面。包含代码片段和最佳实践。",
      url: "https://x.com/openclaw/status/1234567891",
      author: "@openclaw",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 8),
      heatScore: 7.9,
      views: 8760,
      likes: 654,
      comments: 98,
      tags: ["多 agent", "coding", "内容工厂"],
    },
    {
      titleRaw: "One-person company using OpenClaw just hit $50k MRR 💰",
      titleCn: "使用 OpenClaw 的一人公司月营收突破 5 万美元 💰",
      descriptionRaw: "Case study: How @solofounder built a content automation business with OpenClaw. Full breakdown in the thread.",
      descriptionCn: "案例研究：@solofounder 如何用 OpenClaw 构建内容自动化业务。主题中详细解析。",
      url: "https://x.com/openclaw/status/1234567892",
      author: "@openclaw",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
      heatScore: 9.5,
      views: 34520,
      likes: 2341,
      comments: 456,
      tags: ["一人公司", "内容工厂", "自动化"],
    },
    {
      titleRaw: "New tutorial: Browser control with OpenClaw in 10 minutes ⏱️",
      titleCn: "新教程：10 分钟掌握 OpenClaw 浏览器控制 ⏱️",
      descriptionRaw: "From setup to production. Covers selectors, waits, error handling, and deployment. Link in bio.",
      descriptionCn: "从设置到生产。涵盖选择器、等待、错误处理和部署。链接在简介中。",
      url: "https://x.com/openclaw/status/1234567893",
      author: "@openclaw",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 36),
      heatScore: 6.5,
      views: 5670,
      likes: 423,
      comments: 67,
      tags: ["浏览器控制", "coding", "自动化"],
    },
    {
      titleRaw: "OpenClaw v2.3 released: Node management just got easier 🎯",
      titleCn: "OpenClaw v2.3 发布：节点管理变得更简单 🎯",
      descriptionRaw: "New features: auto-scaling, health checks, and one-click deployment. Upgrade now!",
      descriptionCn: "新功能：自动扩展、健康检查和一键部署。立即升级！",
      url: "https://x.com/openclaw/status/1234567894",
      author: "@openclaw",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 72),
      heatScore: 7.1,
      views: 7890,
      likes: 567,
      comments: 89,
      tags: ["节点/node", "自动化", "coding"],
    },
    {
      titleRaw: "Hot take: OpenClaw webhooks replace 80% of Zapier use cases 🔥",
      titleCn: "观点：OpenClaw webhooks 可替代 80% 的 Zapier 用例 🔥",
      descriptionRaw: "Here's why native webhooks are better for automation. Thread with examples.",
      descriptionCn: "为什么原生 webhooks 更适合自动化。包含示例的主题。",
      url: "https://x.com/openclaw/status/1234567895",
      author: "@automation_guru",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 4),
      heatScore: 8.2,
      views: 11230,
      likes: 789,
      comments: 134,
      tags: ["webhook", "自动化", "一人公司"],
    },
    {
      titleRaw: "Building a news aggregator with OpenClaw multi-agent system 📰",
      titleCn: "用 OpenClaw 多 agent 系统构建新闻聚合器 📰",
      descriptionRaw: "5 agents, 50 sources, fully automated. Code walkthrough in the repo.",
      descriptionCn: "5 个 agent，50 个来源，完全自动化。代码演示在仓库中。",
      url: "https://x.com/openclaw/status/1234567896",
      author: "@code_builder",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 18),
      heatScore: 7.4,
      views: 6540,
      likes: 478,
      comments: 72,
      tags: ["多 agent", "内容工厂", "coding"],
    },
    {
      titleRaw: "PSA: OpenClaw now supports headless Chrome on ARM nodes 🍊",
      titleCn: "公告：OpenClaw 现在支持 ARM 节点上的无头 Chrome 🍊",
      descriptionRaw: "Perfect for Raspberry Pi deployments. 40% cost reduction for home labs.",
      descriptionCn: "非常适合树莓派部署。家庭实验室成本降低 40%。",
      url: "https://x.com/openclaw/status/1234567897",
      author: "@openclaw",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 120),
      heatScore: 5.5,
      views: 3450,
      likes: 234,
      comments: 45,
      tags: ["节点/node", "浏览器控制", "自动化"],
    },
  ],
  blog: [
    {
      titleRaw: "The Complete Guide to OpenClaw Automation",
      titleCn: "OpenClaw 自动化完全指南",
      descriptionRaw: "Everything you need to know about building automation workflows with OpenClaw. From basics to advanced patterns.",
      descriptionCn: "使用 OpenClaw 构建自动化工作流所需了解的一切。从基础到高级模式。",
      url: "https://docs.openclaw.ai/guides/automation",
      author: "OpenClaw Team",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7),
      heatScore: 8.3,
      views: 15670,
      likes: 1023,
      comments: 187,
      tags: ["自动化", "coding", "一人公司"],
    },
    {
      titleRaw: "Building Content Factories: A Technical Deep Dive",
      titleCn: "构建内容工厂：技术深度解析",
      descriptionRaw: "How to architect a scalable content generation system using OpenClaw agents, webhooks, and queue management.",
      descriptionCn: "如何使用 OpenClaw agent、webhooks 和队列管理构建可扩展的内容生成系统。",
      url: "https://docs.openclaw.ai/blog/content-factories",
      author: "Engineering Team",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3),
      heatScore: 9.2,
      views: 21340,
      likes: 1567,
      comments: 289,
      tags: ["内容工厂", "多 agent", "webhook"],
    },
    {
      titleRaw: "OpenClaw Browser Control: Best Practices",
      titleCn: "OpenClaw 浏览器控制：最佳实践",
      descriptionRaw: "Learn the dos and don'ts of browser automation. Avoid common pitfalls and build robust scrapers.",
      descriptionCn: "学习浏览器自动化的注意事项。避免常见陷阱并构建健壮的抓取器。",
      url: "https://docs.openclaw.ai/guides/browser-best-practices",
      author: "QA Team",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10),
      heatScore: 7.6,
      views: 9870,
      likes: 678,
      comments: 123,
      tags: ["浏览器控制", "coding", "自动化"],
    },
    {
      titleRaw: "Multi-Agent Orchestration Patterns",
      titleCn: "多 Agent 协调模式",
      descriptionRaw: "Design patterns for coordinating multiple OpenClaw agents. Master-worker, pipeline, and fan-out patterns explained.",
      descriptionCn: "协调多个 OpenClaw agent 的设计模式。详解主从、流水线和扇出模式。",
      url: "https://docs.openclaw.ai/patterns/multi-agent",
      author: "Architecture Team",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14),
      heatScore: 6.9,
      views: 7650,
      likes: 512,
      comments: 98,
      tags: ["多 agent", "自动化", "coding"],
    },
    {
      titleRaw: "Deploying OpenClaw on Kubernetes",
      titleCn: "在 Kubernetes 上部署 OpenClaw",
      descriptionRaw: "Production-ready deployment guide for OpenClaw on K8s. Includes Helm charts and monitoring setup.",
      descriptionCn: "OpenClaw 在 K8s 上的生产就绪部署指南。包含 Helm charts 和监控设置。",
      url: "https://docs.openclaw.ai/deployment/kubernetes",
      author: "DevOps Team",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 21),
      heatScore: 6.1,
      views: 4560,
      likes: 312,
      comments: 56,
      tags: ["节点/node", "coding", "自动化"],
    },
    {
      titleRaw: "Webhook Integration Patterns for OpenClaw",
      titleCn: "OpenClaw 的 Webhook 集成模式",
      descriptionRaw: "How to design robust webhook integrations. Error handling, retries, and security considerations.",
      descriptionCn: "如何设计健壮的 webhook 集成。错误处理、重试和安全考虑。",
      url: "https://docs.openclaw.ai/integrations/webhooks",
      author: "Integration Team",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5),
      heatScore: 8.0,
      views: 11230,
      likes: 823,
      comments: 145,
      tags: ["webhook", "自动化", "coding"],
    },
    {
      titleRaw: "Solo Founder's Guide to OpenClaw",
      titleCn: "一人创始人的 OpenClaw 指南",
      descriptionRaw: "How to build and scale a business alone using OpenClaw automation. Real examples and revenue numbers.",
      descriptionCn: "如何独自使用 OpenClaw 自动化构建和扩展业务。真实案例和收入数据。",
      url: "https://docs.openclaw.ai/guides/solo-founder",
      author: "Community Team",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
      heatScore: 9.0,
      views: 19870,
      likes: 1456,
      comments: 267,
      tags: ["一人公司", "内容工厂", "自动化"],
    },
    {
      titleRaw: "OpenClaw Performance Tuning Guide",
      titleCn: "OpenClaw 性能调优指南",
      descriptionRaw: "Optimize your OpenClaw deployments for speed and cost. Caching, pooling, and parallelization strategies.",
      descriptionCn: "优化 OpenClaw 部署的速度和成本。缓存、池化和并行化策略。",
      url: "https://docs.openclaw.ai/guides/performance",
      author: "Performance Team",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30),
      heatScore: 5.2,
      views: 3210,
      likes: 198,
      comments: 34,
      tags: ["节点/node", "coding", "自动化"],
    },
  ],
  github: [
    {
      titleRaw: "openclaw/browser-automation: Production-ready browser automation toolkit",
      titleCn: "openclaw/browser-automation：生产就绪的浏览器自动化工具包",
      descriptionRaw: "A comprehensive toolkit for browser automation with OpenClaw. Includes selectors, waits, and error recovery.",
      descriptionCn: "使用 OpenClaw 进行浏览器自动化的综合工具包。包括选择器、等待和错误恢复。",
      url: "https://github.com/openclaw/browser-automation",
      author: "openclaw",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15),
      heatScore: 7.8,
      views: 8920,
      likes: 567,
      comments: 89,
      tags: ["浏览器控制", "coding", "自动化"],
    },
    {
      titleRaw: "awesome-openclaw: Curated list of OpenClaw resources",
      titleCn: "awesome-openclaw：OpenClaw 资源精选列表",
      descriptionRaw: "Community-maintained list of tutorials, tools, and examples for OpenClaw. 500+ stars!",
      descriptionCn: "社区维护的 OpenClaw 教程、工具和示例列表。500+ stars！",
      url: "https://github.com/openclaw/awesome-openclaw",
      author: "openclaw",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45),
      heatScore: 6.4,
      views: 5430,
      likes: 389,
      comments: 67,
      tags: ["自动化", "一人公司", "内容工厂"],
    },
    {
      titleRaw: "openclaw/webhook-handlers: Ready-to-use webhook templates",
      titleCn: "openclaw/webhook-handlers：即用型 webhook 模板",
      descriptionRaw: "Pre-built webhook handlers for common automation scenarios. Slack, Discord, Email, and more.",
      descriptionCn: "常见自动化场景的预构建 webhook 处理器。Slack、Discord、邮件等。",
      url: "https://github.com/openclaw/webhook-handlers",
      author: "openclaw",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8),
      heatScore: 8.1,
      views: 10230,
      likes: 734,
      comments: 112,
      tags: ["webhook", "自动化", "coding"],
    },
    {
      titleRaw: "content-factory-starter: OpenClaw content generation template",
      titleCn: "content-factory-starter：OpenClaw 内容生成模板",
      descriptionRaw: "Starter template for building content factories. Includes multi-agent coordination and queue management.",
      descriptionCn: "构建内容工厂的入门模板。包括多 agent 协调和队列管理。",
      url: "https://github.com/openclaw/content-factory-starter",
      author: "openclaw",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4),
      heatScore: 8.6,
      views: 12450,
      likes: 923,
      comments: 156,
      tags: ["内容工厂", "多 agent", "coding"],
    },
    {
      titleRaw: "openclaw-node-manager: Kubernetes operator for OpenClaw",
      titleCn: "openclaw-node-manager：OpenClaw 的 Kubernetes 操作员",
      descriptionRaw: "Deploy and manage OpenClaw nodes on Kubernetes. Auto-scaling and self-healing included.",
      descriptionCn: "在 Kubernetes 上部署和管理 OpenClaw 节点。包括自动扩展和自愈。",
      url: "https://github.com/openclaw/node-manager",
      author: "openclaw",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20),
      heatScore: 6.7,
      views: 4890,
      likes: 345,
      comments: 56,
      tags: ["节点/node", "coding", "自动化"],
    },
    {
      titleRaw: "solo-founder-toolkit: Automation templates for one-person businesses",
      titleCn: "solo-founder-toolkit：一人企业的自动化模板",
      descriptionRaw: "Complete automation setups for solo founders. Content, social, email, and customer support.",
      descriptionCn: "一人创始人的完整自动化设置。内容、社交、邮件和客户支持。",
      url: "https://github.com/openclaw/solo-founder-toolkit",
      author: "openclaw",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6),
      heatScore: 9.3,
      views: 18760,
      likes: 1345,
      comments: 234,
      tags: ["一人公司", "自动化", "内容工厂"],
    },
  ],
  xiaohongshu: [
    {
      titleRaw: "一个人用 OpenClaw 做自动化，月入 5 万是什么体验",
      titleCn: "一个人用 OpenClaw 做自动化，月入 5 万是什么体验",
      descriptionRaw: "分享我作为一人公司使用 OpenClaw 构建内容工厂的经验。从 0 到月入 5 万的全过程。",
      descriptionCn: "分享我作为一人公司使用 OpenClaw 构建内容工厂的经验。从 0 到月入 5 万的全过程。",
      url: "https://xiaohongshu.com/discovery/item/64a1b2c3d4e5f6",
      author: "自动化小姐姐",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 5),
      heatScore: 9.7,
      views: 45670,
      likes: 3456,
      comments: 567,
      tags: ["一人公司", "内容工厂", "自动化"],
    },
    {
      titleRaw: "OpenClaw 浏览器控制教程，10 分钟上手",
      titleCn: "OpenClaw 浏览器控制教程，10 分钟上手",
      descriptionCn: "新手友好的 OpenClaw 浏览器控制教程。包含代码示例和常见问题解答。",
      descriptionRaw: "新手友好的 OpenClaw 浏览器控制教程。包含代码示例和常见问题解答。",
      url: "https://xiaohongshu.com/discovery/item/64a1b2c3d4e5f7",
      author: "代码达人",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 15),
      heatScore: 8.4,
      views: 23450,
      likes: 1890,
      comments: 234,
      tags: ["浏览器控制", "coding", "自动化"],
    },
    {
      titleRaw: "打工人如何用 OpenClaw 摸鱼还能涨工资",
      titleCn: "打工人如何用 OpenClaw 摸鱼还能涨工资",
      descriptionRaw: "用 OpenClaw 自动化日常工作，省下时间学习新技术。老板还觉得你很高效！",
      descriptionCn: "用 OpenClaw 自动化日常工作，省下时间学习新技术。老板还觉得你很高效！",
      url: "https://xiaohongshu.com/discovery/item/64a1b2c3d4e5f8",
      author: "职场生存指南",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 28),
      heatScore: 9.1,
      views: 38920,
      likes: 2890,
      comments: 456,
      tags: ["自动化", "一人公司", "webhook"],
    },
    {
      titleRaw: "OpenClaw 多 agent 配置，效率翻倍",
      titleCn: "OpenClaw 多 agent 配置，效率翻倍",
      descriptionRaw: "教你配置多个 agent 并行处理任务。原本 1 小时的工作，现在 10 分钟搞定。",
      descriptionCn: "教你配置多个 agent 并行处理任务。原本 1 小时的工作，现在 10 分钟搞定。",
      url: "https://xiaohongshu.com/discovery/item/64a1b2c3d4e5f9",
      author: "效率工具控",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 40),
      heatScore: 7.8,
      views: 15670,
      likes: 1234,
      comments: 189,
      tags: ["多 agent", "自动化", "coding"],
    },
    {
      titleRaw: "我用 OpenClaw 搭建了一个内容工厂",
      titleCn: "我用 OpenClaw 搭建了一个内容工厂",
      descriptionRaw: "每天自动产出 100+ 篇内容，全部用 OpenClaw webhook 触发。详细配置教程来了！",
      descriptionCn: "每天自动产出 100+ 篇内容，全部用 OpenClaw webhook 触发。详细配置教程来了！",
      url: "https://xiaohongshu.com/discovery/item/64a1b2c3d4e5fa",
      author: "内容创作者",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 10),
      heatScore: 8.9,
      views: 28760,
      likes: 2123,
      comments: 345,
      tags: ["内容工厂", "webhook", "自动化"],
    },
    {
      titleRaw: "OpenClaw 节点部署，树莓派也能跑",
      titleCn: "OpenClaw 节点部署，树莓派也能跑",
      descriptionRaw: "低成本部署 OpenClaw 节点教程。树莓派 4B 就能跑，适合家庭实验室。",
      descriptionCn: "低成本部署 OpenClaw 节点教程。树莓派 4B 就能跑，适合家庭实验室。",
      url: "https://xiaohongshu.com/discovery/item/64a1b2c3d4e5fb",
      author: "硬件玩家",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 60),
      heatScore: 6.5,
      views: 8920,
      likes: 678,
      comments: 98,
      tags: ["节点/node", "coding", "自动化"],
    },
    {
      titleRaw: " webhook 配置详解，OpenClaw 集成必备",
      titleCn: "webhook 配置详解，OpenClaw 集成必备",
      descriptionRaw: "OpenClaw webhook 完整配置教程。集成飞书、钉钉、企业微信都靠它。",
      descriptionCn: "OpenClaw webhook 完整配置教程。集成飞书、钉钉、企业微信都靠它。",
      url: "https://xiaohongshu.com/discovery/item/64a1b2c3d4e5fc",
      author: "集成专家",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 22),
      heatScore: 7.6,
      views: 12340,
      likes: 956,
      comments: 134,
      tags: ["webhook", "自动化", "coding"],
    },
    {
      titleRaw: "从 0 开始用 OpenClaw 做自媒体",
      titleCn: "从 0 开始用 OpenClaw 做自媒体",
      descriptionRaw: "一个人运营 5 个账号，全靠 OpenClaw 自动化。分享我的内容工厂搭建经验。",
      descriptionCn: "一个人运营 5 个账号，全靠 OpenClaw 自动化。分享我的内容工厂搭建经验。",
      url: "https://xiaohongshu.com/discovery/item/64a1b2c3d4e5fd",
      author: "自媒体创业者",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 8),
      heatScore: 8.8,
      views: 25670,
      likes: 1987,
      comments: 289,
      tags: ["内容工厂", "一人公司", "自动化"],
    },
  ],
};

// 标签分类映射
const tagCategories: Record<string, string> = {
  "自动化": "PLAYSTYLE",
  "浏览器控制": "TOOL",
  "coding": "TOOL",
  "多 agent": "PLAYSTYLE",
  "节点/node": "PLATFORM",
  "webhook": "TOOL",
  "一人公司": "PLAYSTYLE",
  "内容工厂": "PLAYSTYLE",
};

async function createTags() {
  const tags = Object.keys(tagCategories);
  for (const tagName of tags) {
    await prisma.tag.upsert({
      where: { name: tagName },
      update: {},
      create: {
        name: tagName,
        category: tagCategories[tagName],
        description: `${tagName} 相关内容`,
      },
    });
  }
  console.log(`✅ Created ${tags.length} tags`);
}

async function seedItems() {
  let totalCreated = 0;
  
  for (const [sourceType, items] of Object.entries(mockData)) {
    console.log(`\n📥 Seeding ${sourceType}...`);
    
    for (const item of items) {
      const existing = await prisma.item.findUnique({
        where: { url: item.url },
      });

      if (existing) {
        console.log(`  ⏭️  Skipped: ${item.titleRaw.substring(0, 40)}...`);
        continue;
      }

      // Create item
      const created = await prisma.item.create({
        data: {
          sourceType,
          sourceId: item.url.split('/').pop() || item.url,
          url: item.url,
          titleRaw: item.titleRaw,
          titleCn: item.titleCn,
          descriptionRaw: item.descriptionRaw,
          descriptionCn: item.descriptionCn,
          author: item.author,
          publishedAt: item.publishedAt,
          fetchedAt: new Date(),
          status: Math.random() > 0.3 ? 'PUBLISHED' : 'PENDING', // 70% published
          heatScore: item.heatScore,
          views: item.views,
          likes: item.likes,
          comments: item.comments,
        },
      });

      // Add tags
      for (const tagName of item.tags) {
        const tag = await prisma.tag.findUnique({
          where: { name: tagName },
        });
        if (tag) {
          await prisma.itemTag.create({
            data: {
              itemId: created.id,
              tagId: tag.id,
            },
          });
        }
      }

      totalCreated++;
      console.log(`  ✅ Created: ${item.titleCn}`);
    }
  }

  console.log(`\n🎉 Total items created: ${totalCreated}`);
}

async function main() {
  console.log('🌱 Starting mock data seeding...\n');
  
  await createTags();
  await seedItems();
  
  console.log('\n✅ Seeding complete!');
  process.exit(0);
}

main().catch((e) => {
  console.error('❌ Seeding failed:', e);
  process.exit(1);
});
